(function(){'use strict';
const u=YMS_Auth?.getUser?.();if(!u||!window._tFetch)return;
const role=String(u.role||'').toUpperCase(),admin=role==='ADMIN',teacher=role==='TEACHER'||YMS_Roles?.has?.(u,'TEACHER'),base=_tFetch,home=/\/(student-home|parent-home)\.html$/.test(location.pathname);
let names=new Set();
const csv=v=>Array.isArray(v)?v:String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
async function scope(){try{
if(teacher&&!admin){const r=await base('tables/classes?limit=300');if(r.ok){const j=await r.json(),a=csv(u.teacherClasses);(j.data||[]).filter(c=>c.teacherId===u.id||c.teacherId===u.uid||c.teacherName===u.name||a.includes(c.id)||a.includes(c.className)).forEach(c=>c.className&&names.add(c.className));}}
if(role==='STUDENT'){const id=u.studentId||u._tableId;if(id){const r=await base('tables/students/'+encodeURIComponent(id));if(r.ok){const s=await r.json();if(s.className)names.add(s.className);}}}
if(role==='PARENT')for(const id of csv(u.childIds)){const r=await base('tables/students/'+encodeURIComponent(id));if(r.ok){const s=await r.json();if(s.className)names.add(s.className);}}
}catch(e){console.warn('[YMS] notice scope',e)}}
function show(n){if(admin)return true;const t=String(n.targetType||'ALL').toUpperCase();return t==='ALL'||(t==='ROLE'&&String(n.targetRole||'').toUpperCase()===role)||(t==='CLASS'&&names.has(n.targetClassName));}
function resp(data){if(home)data=data.map(n=>String(n.targetType||'ALL').toUpperCase()==='ALL'?n:{...n,targetType:'ALL'});return{ok:true,status:200,json:async()=>({data,total:data.length}),text:async()=>JSON.stringify({data,total:data.length})}}
async function wrap(){const old=window._tFetch;if(old.__notice)return;const f=async(p,o={})=>{const m=String(o.method||'GET').toUpperCase(),s=String(p||'');if(!s.startsWith('tables/notices'))return old(p,o);if(m==='GET'){const r=await old(p,o);if(s.includes('?')&&r.ok&&!admin){const j=await r.json();return resp((j.data||[]).filter(show));}return r;}if(admin)return old(p,o);let b={};try{b=o.body?JSON.parse(o.body):{}}catch{}if(m==='POST'&&teacher&&String(b.targetType).toUpperCase()==='CLASS'&&names.has(b.targetClassName))return old(p,o);if((m==='PATCH'||m==='DELETE')&&teacher){const id=s.split('/').pop(),n=(typeof _allNotices!=='undefined'&&Array.isArray(_allNotices))?_allNotices.find(x=>x.id===id):null;if(n&&n.authorId===(u.id||u.uid)&&String(n.targetType).toUpperCase()==='CLASS'&&names.has(n.targetClassName))return old(p,o);}return{ok:false,status:403,json:async()=>({error:'DENIED'}),text:async()=>'DENIED'};};f.__notice=true;window._tFetch=f;}
function page(){if(!location.pathname.endsWith('/notices.html'))return;const w=document.getElementById('writeBtn'),sel=document.getElementById('noticeTarget');if(w)w.classList.toggle('hidden',!(admin||teacher));if(sel){if(admin)sel.innerHTML='<option value="ALL">전체</option><option value="ROLE:TEACHER">선생님</option><option value="ROLE:STUDENT">학생</option><option value="ROLE:PARENT">학부모</option>';else if(teacher)sel.innerHTML=[...names].sort((a,b)=>a.localeCompare(b,'ko')).map(n=>'<option value="CLASS:'+n+'">'+n+'</option>').join('')||'<option value="">담당 반 없음</option>';}
if(!(admin||teacher))return;window.submitNotice=async e=>{e.preventDefault();const b=document.getElementById('noticeSubmitBtn');if(b){b.disabled=true;b.textContent='등록 중...'}try{const raw=sel?.value||'ALL';let tt='ALL',tr='',tc='';if(raw.startsWith('ROLE:')){tt='ROLE';tr=raw.slice(5);tc={TEACHER:'선생님',STUDENT:'학생',PARENT:'학부모'}[tr]||''}else if(raw.startsWith('CLASS:')){tt='CLASS';tc=raw.slice(6)}const p={title:noticeTitle.value.trim(),content:noticeContent.value.trim(),noticeType:noticeType.value,targetType:tt,targetRole:tr,targetClassName:tc,authorId:u.id||u.uid||'',authorName:u.name||'',authorRole:admin?'ADMIN':'TEACHER',publishedAt:new Date().toISOString(),isActive:true};const r=await _tFetch('tables/notices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error('공지 저장 실패');writeModal.classList.add('hidden');noticeRegForm.reset();YMS_UI.toast('공지가 등록되었습니다! 📢');if(typeof loadNotices==='function')await loadNotices();else location.reload();}catch(x){YMS_UI.toast('❌ '+x.message)}finally{if(b){b.disabled=false;b.textContent='등록하기'}}};}
(async()=>{await scope();await wrap();page();if(location.pathname.endsWith('/notices.html')&&typeof loadNotices==='function')setTimeout(()=>loadNotices(),50)})();})();